### PR TITLE
Ensure the access to the FrameCollection class is synchronised

### LINKED ISSUE #249: Receiving segmentation fault when testing on GitHub Actions + Linux
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We're using memray to limit memory usage during a test which reads large chunks of data and decompresses them before returning to the user. On macOS everything works fine but on Linux we're sometimes receiving segmentation faults and other Python internal errors:

- https://github.com/urllib3/urllib3/actions/runs/3445672571/jobs/5749660305
- https://github.com/urllib3/urllib3/actions/runs/3445672571/jobs/5749660206

Copying one output here to ensure GHA doesn't delete the logs:
<details>
  <summary>Log</summary>

```
Fatal Python error: Segmentation fault

Thread 0x00007fab496ff640 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/selectors.py", line 469 in select
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 1869 in _run_once
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 601 in run_forever
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/base_events.py", line 634 in run_until_complete
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/asyncio/runners.py", line 44 in run
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 240 in _run_and_close_tornado
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/concurrent/futures/thread.py", line 58 in run
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/concurrent/futures/thread.py", line 83 in _worker
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 917 in run
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007fab33fff640 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 312 in wait
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 581 in wait
  File "/home/runner/work/urllib3/urllib3/dummyserver/testcase.py", line 86 in socket_handler
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 146 in _start_server
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 150 in run
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 937 in _bootstrap

Current thread 0x00007fab43fff640 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/ssl.py", line 1102 in read
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/ssl.py", line 1227 in recv
  File "/home/runner/work/urllib3/urllib3/dummyserver/testcase.py", line 29 in consume_socket
  File "/home/runner/work/urllib3/urllib3/test/test_ssltransport.py", line 118 in socket_handler
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 146 in _start_server
  File "/home/runner/work/urllib3/urllib3/dummyserver/server.py", line 150 in run
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 980 in _bootstrap_inner
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/threading.py", line 937 in _bootstrap

Thread 0x00007fab5033eb80 (most recent call first):
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/socket.py", line 954 in getaddrinfo
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/util/connection.py", line 58 in create_connection
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 208 in _new_conn
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 244 in connect
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/http/client.py", line 980 in send
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/http/client.py", line 1040 in _send_output
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/http/client.py", line 1280 in endheaders
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connection.py", line 392 in request
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 497 in _make_request
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 791 in urlopen
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/_request_methods.py", line 140 in request_encode_url
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/urllib3/_request_methods.py", line 107 in request
  File "/home/runner/work/urllib3/urllib3/test/with_dummyserver/test_connectionpool.py", line 941 in test_skip_header
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pytest_memray/plugin.py", line 122 in wrapper
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/python.py", line 1789 in runtest
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 260 in <lambda>
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 339 in from_call
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/flaky/flaky_pytest_plugin.py", line 138 in call_and_report
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/flaky/flaky_pytest_plugin.py", line 94 in pytest_runtest_protocol
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/main.py", line 324 in _main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 167 in main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/coverage/execfile.py", line 199 in run
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/coverage/cmdline.py", line 830 in do_run
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/coverage/cmdline.py", line 659 in command_line
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/coverage/cmdline.py", line 943 in main
  File "/home/runner/work/urllib3/urllib3/.nox/test-3-9/lib/python3.9/site-packages/coverage/__main__.py", line 8 in <module>
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/runpy.py", line 87 in _run_code
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/runpy.py", line 197 in _run_module_as_main
nox > Command python -bb -m coverage run --parallel-mode -m pytest --memray --hide-memray-summary -r a --color=yes --tb=native --no-success-flaky-report test/ failed with exit code -11
nox > Session test-3.9 failed.
```

</details>

You can see the PR where we initially added memray support here: https://github.com/urllib3/urllib3/pull/2798

### Expected Behavior

No segfault or crashes to happen on Linux

### Steps To Reproduce

- (On Linux + GHA)
- Clone urllib3 repo
- Install nox
- Run `$ nox -rs test-3.9 -- test/test_response.py::TestBytesQueueBuffer.test_memory_usage`1
- Sometimes segmentation fault?

### Memray Version

1.3.0

### Python Version

3.8, 3.9, 3.10, 3.11

### Operative System

Linux

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by pablogsal**
When we need to register a new Python frame that we have not seen before
or when we need to get the ID of an existing Python frame, we use the
FrameCollection class that manages the collection of known Python
frames. The mutation of this data structure was previously protected by
the GIL as we only do these operations on the Python tracing function,
but since the introduction of lazy frame registering, now operations
over the FrameCollection can happen under the allocation/deallocation
hooks directly, and therefore access is now non synchronised.

This problem is still very difficult to trigger because the only
situation when a race will occur is when two threads compete to write
and read from the FrameCollection at the same time and for this to
happen at least one of these threads needs to make native allocations
without the GIL held with pending frames that the frame collection has
never seen.

Closes #249

### CODE REVIEW

**Comment by pablogsal** [comment]
Note: There will be **no prize** for the first person that suggest to rewrite in Rust :)

File: src/memray/_memray/records.h [hunk 1]
```diff
@@ -259,8 +261,12 @@ class FrameCollection
...
     auto getIndex(T&& frame) -> std::pair<frame_id_t, bool>
     {
+        std::shared_lock<std::shared_mutex> r_lock(d_mutex);
         auto it = d_frame_map.find(frame);
         if (it == d_frame_map.end()) {
+            r_lock.unlock();
+            std::unique_lock<std::shared_mutex> w_lock(d_mutex);
+
             frame_id_t frame_id =
                     d_frame_map.emplace(std::forward<T>(frame), d_current_frame_id).first->second;
```
Comment (godlygeek) [inline src/memray/_memray/records.h:271]: I believe there's a bug here, actually. We can't ignore the return from `emplace`, because `emplace` can fail if the element we're trying to insert was already inserted by another thread.

Imagine:
- 2 threads both want to insert the same frame
- both successfully grab the shared lock
- both see that the frame doesn't exist yet
- both drop the shared lock
- one grabs the unique lock
- it calls emplace, successfully inserting the element
- the first one drops the unique lock, the second acquires it
- the second one calls emplace, failing to insert the element
- we don't notice, and treat it as though a new ID was registered.

**Review by godlygeek — APPROVED** [review]
LGTM, after the update I pushed to respect the `bool` returned by `emplace`
